apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  labels:
    tier: test
spec:
  containers:
    - name: test
      image: busybox
      command: ['sleep', '5000']
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: name
            path: name 
