AWSTemplateFormatVersion: 2010-09-09
Resources:
  cfs3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vinod-cf-0532
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:s3'
